name: Testing k8s

on:
  workflow_dispatch:

jobs:

  jumpbox:
    runs-on: ubuntu-22.04
    steps: &node
    - uses: actions/checkout@v5
      with:
        ref: dev/k8s
    - name: Setup node
      uses: ./.github/actions/setup-node
      with:
        node-name: ${{ github.job }}
        ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
    - name: echo date only
      run: |
        while true; do
          echo $(date);
          sleep 5;
        done
  
  server:
    runs-on: ubuntu-22.04
    steps: *node
  
  node-0:
    runs-on: ubuntu-22.04
    steps: *node
  
  node-1:
    runs-on: ubuntu-22.04
    steps: *node